KA14/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('vendor/',include('vendor.urls')),
    path('',include('helloWorld.urls')),
    path('vendor_list/',include('vendor_list.urls')),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

helloWorld/urls.py
from django.urls import path, include

from helloWorld import views

urlpatterns=[
    path('',views.index),
]

vendor_food/urls.py
from django.urls import path
from vendor_food import views

urlpatterns = [
    path('<str:slug>/', views.addFood)
]

vendor_list/urls.py
from django.urls import path, include
from . import views

app_name = "vendor-list"

urlpatterns = [
        path("", views.vendor_list_page, name="vendor-list-page")
]

helloWorld/models.py
from django.db import models

# Create your models here.

vendor_food/models.py
from django.db import models

# Create your models here.

vendor_list/models.py
from django.db import models

# Create your models here.

vendor_review/models.py
from django.db import models

# Create your models here.

vendor_food/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from vendor.models import Vendor_Food

class addFoods(forms.ModelForm):
    class Meta:
        model = Vendor_Food
        fields = ['name', 'food_image']
        labels = {
                'name': _("Name"),
                'food_image' : _("Food Image")
                }
        

helloWorld/views.py
from django.shortcuts import render
from django.http.response import HttpResponse

# Create your views here.
def index(request):
    return render(request,'homepage.html')

vendor_food/views.py
from django.shortcuts import render, redirect

from vendor.models import Vendor_Food, Vendor
from vendor_food.forms import addFoods

# Create your views here.
def addFood(request, slug):
    vendor = Vendor.objects.get(slug=slug)
    if (request.method == "POST"):
        forms = addFoods(request.POST, request.FILES)
        if(forms.is_valid()):
            instance = forms.save(commit=False)
            instance.store_id = vendor.id 
            instance.store_name = vendor.name
            instance.save()
            return redirect('/vendor/food/'+slug+"/")
        else:
            foods = Vendor_Food.objects.filter(store_id=vendor.id)
            return render(request, 'vendor_food/foods.html', {'form': forms, 'info': vendor, 'foods':foods})

    foods = Vendor_Food.objects.filter(store_id=vendor.id)
    return render(request, 'vendor_food/foods.html', {'form': addFoods(), 'info': vendor, 'slug':slug, 'foods':foods})

vendor_list/views.py
from django.shortcuts import render,redirect
from vendor.models import Vendor
from .form import Vendor_form
# Create your views here.

# def vendor_list_page(request):
#     vendors = Vendor.objects.all()
#     return render(request,"vendor_list/vendor_page.html", {'vendors':vendors, 'counter':range(3)})

def vendor_list_page(request):
    if request.method=="POST":
        form = Vendor_form(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            return redirect("/vendor_list/")
            # vendor = Vendor(
            #     name = form.cleaned_data['name'],
            #     info = form.cleaned_data['info'],
            #     price_level = form.cleaned_data['price_level'],
            #     food_type = form.cleaned_data['food_type'],
            #     website = form.cleaned_data['website'],
            #     email = form.cleaned_data['email'],
            #     phone = form.cleaned_data['phone'],
            #     vendor_picture = form.cleaned_data['vendor_picture'],
            # )
            # vendor.save()
        vendors = Vendor.objects.all()    
        return render(request,"vendor_list/vendor_page.html", {'vendors':vendors, "forms":form}) 
    form = Vendor_form()
    vendors = Vendor.objects.all()    
    return render(request,"vendor_list/vendor_page.html", {'vendors':vendors, "forms":form})

vendor_review/views.py
from django.shortcuts import render

# Create your views here.

templates/base.html
{% load static from staticfiles %}

<!doctype html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport"
              content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css?family=Radley|Ruthie&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'base.css' %}">
        <link rel="stylesheet" href="{% static 'navbar.css' %}">
        <link rel="stylesheet" href="{% static 'vendor/vendor_list.css' %}">
        <link rel="stylesheet" href="{% static 'vendor/style_info.css' %}">
        <link rel="stylesheet" href="{% static 'homepage.css' %}">
        <title>Merrit</title>
    </head>
    <body>
            <nav class="navbar navbar-expand navbar-light container" id="navbar">
              <a class="navbar-brand" href="/" style="font-family: 'Ruthie', cursive;">Merrit</a>
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto">
                  <li class="nav-item">
                    <a class="nav-link" href="/" id="home">Home</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="/vendor_list/" id="vendors">Vendors</a>
                  </li>
                  <li class="nav-item">
                      <a href="#" class="nav-link" id="about">About Us</a>
                  </li>
                </ul>
              </div>
            </nav>
        <div>
            {% block content %}
            {% endblock %}
        </div>
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        <script>
            let isHomepage = document.getElementById('homepage');
            let isVendor = document.getElementById('vendors-lists');
            let isVendorInfo = document.getElementById('vendor-info');
            let menus = document.getElementsByClassName("nav-link");

            if(isHomepage !== null){
                document.getElementById('navbar').classList.add("fixed-top")
                activate('home')
            }else if(isVendor !== null || isVendorInfo !== null){
                activate('vendors')
            }

            function activate(id) {
                for (var i = 0; i < menus.length; i++) {
                    menus[i].classList.remove("active");
                }
                document.getElementById(id).classList.add("active")
            }
        </script>
    </body>
</html>

templates/homepage.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="container-fluid" id="homepage">
        <div class="row justify-content-center opening">
            <div class="col-md-4 offset-md-1 align-self-center opening-text">
                <h1>Looking For Catering For Your Wedding?</h1>
                <p style="max-width: 450px; margin-bottom: 2rem;">Lucky for you, we have more than 20.000 catering vendors waiting to serve you. All sertificated and has been rated.</p>
                <a href="/vendor_list/" class="no-style" style="color: white;
                    background-color: #DD5757;
                    border-radius: 20px;
                    padding: 0.5rem;
                    text-decoration: none;
                    ">Get Started</a>
            </div>
            <img class="img-homepage" src="{% static 'homepage.svg' %}" alt="">
        </div>
    </div>
{% endblock %}

templates/vendor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    
</body>
</html>

vendor_food/templates/vendor_food/foods.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container" style="margin-top: 1rem;" id="vendor-info">
        <div class="row justify-content-center">
            <div class="col-3 card-vendor" style="box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);">
                <div class="satu">
                    <img src= "{{ info.vendor_picture.url }}" class="img-fluid">
                    <p id="title">{{ info.name }}</p>
                    <div class="row justify-content-between">
                        <p class="col-6 font">{{ info.food_type }}</p>
                        <div class="col-auto font">{{ info.price_level }} | {{ info.get_star_ammount }} <img src="{% static 'vendor/Star_4.svg' %}" width="25px" height="25px"></div>
                    </div>
                    <hr>
                    <p class="font"><img src= "{% static 'vendor/Vector.svg' %}" width="20px" height="20px" class="img-fluid"> {{ info.website }}</p>
                    <p class="font"><img src= "{% static 'vendor/@.svg' %}" width="20px" height="20px" class="img-fluid"> {{ info.email }}</p>
                    <p class="font"><img src= "{% static 'vendor/call.svg' %}" width="20px" height="20px" class="img-fluid">{{ info.phone }}</p>
                </div>
            </div>

            <div class="col-7" style="border: #848484 solid 0.5px; padding: 0;">
                <div class="text-center menu-wrapper no-style" style="border: #848484 solid 0.5px">
                    <a class="active-info menu font-title" href="/vendor/food/{{ info.slug }}/" style="border-right: #848484 solid 0.5px">
                        Food
                    </a>
                    <a class="menu font-title" href="/vendor/review/{{ info.slug }}/" style="border-right: #848484 solid 0.5px">
                        Reviews
                    </a>
                    <a class="menu font-title" href="/vendor/{{ info.slug }}/">
                        Info & Pricing
                    </a>
                </div>
                <div class="row justify-content-center">
                    <div class="container-fluid">
                        <div class="row" style="max-width: 100%">
                            <button type="button" class="btn no-style ml-auto" data-toggle="modal" data-target="#exampleModalCenter">
                                    + Add Foods
                                </button>
                        </div>
                                
                                <!-- Modal -->
                                <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle"
                                    aria-hidden="true">
                                    <div class="modal-dialog modal-dialog-centered" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="exampleModalLongTitle">Add Food</h5>
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                            <form class="food-form" action="/vendor/food/{{ slug }}/" method="POST" enctype="multipart/form-data">
                                                {% csrf_token %}
                                                <div class="modal-body">
                                                    {{ form }}
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                                    <button type="submit" class="btn btn-primary">Add Food</button>
                                                </div>
                                
                                            </form>
                                
                                        </div>
                                    </div>
                                </div>
                                <div class="row justify-content-center" style="overflow-y: auto; max-height: 50vh;">
                                    {% for food in foods %}
                                    <div class="col-md-5 mx-auto mb-3">
                                            <div class="row">
                                                    <img src="{{ food.food_image.url }}" class="img-fluid">
                                                <div class="col-4">
                                                    <h5>{{ food.name }}</h5>
                                                    <br>
                                                    <h6 style="color: #848484; font-style: italic;">{{ food.store_name }}</h6>
                                                </div>
                                            </div>
                                        </div>
                                    {% endfor %}
                                </div>
                                
                                </div>
                    </div>
                </div>
            </div>
        </div>
    </div>




{% endblock %}

vendor_list/templates/vendor_list/vendor_page.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <div class="row" style="max-width: 100%">
        <button type="button" class="btn no-style ml-auto" data-toggle="modal" data-target="#exampleModalCenter">
            + Add Vendor
        </button>
    </div>
        <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalCenterTitle">Add Vendor</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
          </div>
            <form action="{% url 'vendor-list:vendor-list-page' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
              <div class="modal-body">
                    <div class="form-group">
                        {{ forms.name.errors }}
                        <label for="id_name">{{ forms.name.label }}</label>
                        {{ forms.name }}
                    </div>
                    <div class="form-group">
                        <label for="id_star_ammount">{{ forms.info.label }}</label>
                        <div class="input-group">
                            {{ forms.info.errors }}
                            {{ forms.info }}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="id_comment">{{ forms.website.label }}</label>
                        <div class="input-group">
                            {{ forms.website.errors }}
                            {{ forms.website }}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="id_comment">{{ forms.email.label }}</label>
                        <div class="input-group">
                            {{ forms.email.errors }}
                            {{ forms.email }}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="id_comment">{{ forms.phone.label }}</label>
                        <div class="input-group">
                            {{ forms.phone.errors }}
                            {{ forms.phone }}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="id_comment">{{ forms.price_level.label }}</label>
                        <div class="input-group">
                            {{ forms.price_level.errors }}
                            {{ forms.price_level }}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="id_comment">{{ forms.food_type.label }}</label>
                        <div class="input-group">
                            {{ forms.foor_type.errors }}
                            {{ forms.food_type }}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="id_comment">{{ forms.vendor_picture.label }}</label>
                        <div class="input-group">
                            {{ forms.vendor_picture.errors }}
                            {{ forms.vendor_picture }}
                        </div>
                    </div>
                </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="submit" class="btn" style="background-color:pink">Add Vendor</button>
              </div>
            </form>
        </div>
      </div>
    </div>

    <div class="row justify-content-center mx-auto" id="vendors-lists">
    {% for vendor in vendors %}
        <div class="col-12 col-4" id="col-card">
            <div class="card">
                <img class="card-img-top" src="{{ vendor.vendor_picture.url }}" alt="Card image cap">
                <div class="card-body">
                    <a href="/vendor/{{ vendor.slug }}"><h1 class="card-name">{{ vendor.name }}</h1></a>
                    {{ vendor.get_star_ammount }} <img class="img-fluid card-star my-2" src="{% static 'vendor/Star_4.svg' %}" alt="stars">
                    <p class="card-dollar">{{ vendor.get_dollars }}</p>
                    <p class="card-text">{{ vendor.info }}</p>
                </div>
            </div>
        </div>   
    {% endfor %}
    </div>
{% endblock %}

vendor_review/templates/vendor_review/review.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="container" style="margin-top: 1rem;" id="vendor-info">
        <div class="row justify-content-center">
            <div class="col-3 card-vendor" style="box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);">
                <div class="satu">
                    <img src= "{{ info.vendor_picture.url }}" class="img-fluid">
                    <p id="title">{{ info.name }}</p>
                    <div class="row justify-content-between">
                        <p class="col-6 font">{{ info.food_type }}</p>
                        <div class="col-auto font">{{ info.price_level }} | {{ info.get_star_ammount }} <img src="{% static 'vendor/Star_4.svg' %}" width="25px" height="25px"></div>
                    </div>
                    <hr>
                    <p class="font"><img src= "{% static 'vendor/Vector.svg' %}" width="20px" height="20px" class="img-fluid"> {{ info.website }}</p>
                    <p class="font"><img src= "{% static 'vendor/@.svg' %}" width="20px" height="20px" class="img-fluid"> {{ info.email }}</p>
                    <p class="font"><img src= "{% static 'vendor/call.svg' %}" width="20px" height="20px" class="img-fluid">{{ info.phone }}</p>
                </div>
            </div>

            <div class="col-7" style="border: #848484 solid 0.5px; padding: 0;">
                <div class="text-center menu-wrapper no-style" style="border: #848484 solid 0.5px">
                    <a class="menu font-title" href="/vendor/food/{{ info.slug }}/" style="border-right: #848484 solid 0.5px">
                        Food
                    </a>
                    <a class="active-info menu font-title" href="/vendor/review/{{ info.slug }}/" style="border-right: #848484 solid 0.5px">
                        Reviews
                    </a>
                    <a class="menu font-title" href="/vendor/{{ info.slug }}/">
                        Info & Pricing
                    </a>
                </div>
                <div class="row justify-content-center">
                    <div class="container-fluid">
        <div class="row" style="max-width: 100%">
            <button type="button" class="btn no-style ml-auto" data-toggle="modal" data-target="#exampleModalCenter">
                + Add Review
            </button>
        </div>
            <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
          <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalCenterTitle">Add Review</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
                <form action="/vendor/review/{{ slug }}/" method="post">
                    {% csrf_token %}
                  <div class="modal-body">
                        <div class="form-group">
                            <label for="id_name">{{ forms.name.label }}</label>
                            {{ forms.name }}
                        </div>
                        <div class="form-group">
                            <label for="id_star_ammount">{{ forms.star_ammount.label }}</label>
                            <div class="input-group">
                                {{ forms.star_ammount }}
                                 <div class="input-group-append">
                                    <span class="input-group-text" id="basic-addon2">Stars</span>
                                  </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="id_comment">{{ forms.comment.label }}</label>
                            {{ forms.comment }}
                        </div>
                        <input type="hidden" name="store_id" value="{{ something }}">
                    </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn">Add Review</button>
                  </div>
                </form>
            </div>
          </div>
        </div>
    <div class="row justify-content-center" style="overflow-y: auto; max-height: 50vh;">
                {% for review in reviews %}
                    <div class="col-10 mb-3">
                        <div class="row">
                            <div class="col-9">
                                <h5>{{ review.name }}</h5>
                                <h6 style="color: #848484; font-style: italic;">{{ review.date }}</h6>
                            </div>
                            <div class="col-2">
                                <div style="display: flex; flex-direction: row;">
                                    <h6 class="align-self-center mr-2 my-0">{{ review.star_ammount }}</h6>
                                    <img src="{% static 'vendor/Star_4.svg' %}" alt="" class="img-fluid align-self-center" style="max-height: 25px;">
                                </div>
                            </div>
                        </div>
                        <p class="text-justify">{{ review.comment }}</p>
                    </div>
                {% endfor %}
        </div>
    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}